.\" RCSid "$Id: cnt.1,v 1.5 2022/04/11 18:08:19 greg Exp $"
.TH CNT 1 11/15/93 RADIANCE
.SH NAME
cnt - index counter
.SH SYNOPSIS
.B cnt
[
.B \-s
]
N1
[
N2 ..
]
.SH DESCRIPTION
.I Cnt
counts from 0 to N-1, producing N lines of output.
If multiple arguments are given,
.I cnt
produces a nested array of values where the final counter
rotates fastest through its range.
The
.I \-s
option shuffles the output lines, giving a different random
order on each invocation.
.I Cnt
is most useful in conjunction with
.I rcalc(1)
to produce array values.
.SH EXAMPLE
To create a 3 by 5 array:
.IP "" .2i
cnt 3 5
.PP
To generate a random shuffle of indices 0 through 51:
.IP "" .2i
cnt -s 52
.PP
Similar shuffling broken down by suit:
.IP "" .2i
cnt -s 4 13
.SH AUTHOR
Greg Ward
.SH "SEE ALSO"
neaten(1), rcalc(1), rlam(1), rsplit(1), total(1)
